# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/moleculer-postgraphile
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: git clone https://github.com/vishnubob/wait-for-it.git
      - run: chmod +x ./wait-for-it/wait-for-it.sh
      - run:
          name: Start container and verify it is working
          command: npm run provision:dev
      - run:
          name: Waiting for postgres running
          command: ./wait-for-it/wait-for-it.sh localhost:5434
      - run: npm run test:lint

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
