version: '3.1'
services:
  postgrestest:
    # build:
    #   context: ./test-postgres
    #   dockerfile: Dockerfile
    image: postgres:10.5
    container_name: postgrestest
    hostname: postgrestest
    restart: always
    volumes:
      - postgrestest:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 5434:5432
    networks:
      - postgraphile
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123789
      POSTGRES_DB: test

volumes:
  postgrestest:

networks:
  postgraphile:
